#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────
# Aethera — Cloudflare Tunnel Setup (optional bolt-on)
#
# Bindet cloudflared NACHTRÄGLICH ein, schließt den Panel-UI-Port
# auf dem Host und routet das Panel über einen Cloudflare Named
# Tunnel (HTTPS). run.sh merkt sich die Topologie via .aethera.profile,
# sodass spätere up/rebuild/restart sie beibehalten.
#
# Einrichten : ./cloudflared-setup.sh
# Rückbau    : ./cloudflared-setup.sh --remove
#
# WICHTIG: Der Tunnel trägt NUR den HTTP-Panel-Port. Game-Server-Ports
# (TCP 25565 etc.) bleiben unverändert auf dem Host published — Spieler
# verbinden weiterhin direkt zu Host:<port>.
# ─────────────────────────────────────────────

COMPOSE_FILE="docker-compose.yml"
TUNNEL_FILE="docker-compose.tunnel.yml"
PROFILE_FILE=".aethera.profile"

# Colours
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
info() { echo -e "${GREEN}[cloudflared]${NC} $*"; }
warn() { echo -e "${YELLOW}[cloudflared]${NC} $*"; }
err()  { echo -e "${RED}[cloudflared]${NC} $*" >&2; }
step() { echo -e "${BLUE}»${NC} $*"; }

# set_env KEY VALUE  — upsert a key in .env (GNU sed, like run.sh)
set_env() {
  local k="$1" v="$2" esc
  esc=$(printf '%s' "$v" | sed -e 's/[\\&|]/\\&/g')
  if grep -q "^${k}=" .env 2>/dev/null; then
    sed -i "s|^${k}=.*|${k}=${esc}|" .env
  else
    echo "${k}=${v}" >> .env
  fi
}

# ── --remove: Rückbau ─────────────────────────
if [ "${1:-}" = "--remove" ]; then
  warn "Removing Cloudflare tunnel and reopening the panel port..."
  if [ -f "$TUNNEL_FILE" ]; then
    docker compose -f "$COMPOSE_FILE" -f "$TUNNEL_FILE" --profile tunnel rm -sf cloudflared 2>/dev/null || true
  fi
  rm -f "$TUNNEL_FILE" "$PROFILE_FILE"
  [ -f .env ] && set_env APP_BIND 0.0.0.0
  info "Restarting stack with the published port..."
  chmod +x run.sh 2>/dev/null || true
  ./run.sh up
  info "✅  Tunnel removed — panel port is published again."
  exit 0
fi

# ── Preflight ─────────────────────────────────
command -v docker >/dev/null 2>&1 || { err "Docker is not installed."; exit 1; }
docker compose version >/dev/null 2>&1 || { err "Docker Compose v2 is required."; exit 1; }
[ -f .env ] || { err ".env missing — run './run.sh up' once first to bootstrap it."; exit 1; }

# Detect compose version for '!reset' support (>= 2.24.0)
COMPOSE_VER=$(docker compose version --short 2>/dev/null | tr -d 'v ' || echo "0.0.0")
supports_reset() {
  local maj min
  maj=$(echo "$COMPOSE_VER" | cut -d. -f1)
  min=$(echo "$COMPOSE_VER" | cut -d. -f2)
  [ "${maj:-0}" -gt 2 ] 2>/dev/null && return 0
  { [ "${maj:-0}" -eq 2 ] && [ "${min:-0}" -ge 24 ]; } 2>/dev/null && return 0
  return 1
}

echo ""
info "Cloudflare Tunnel setup for the Aethera panel"
echo ""
echo "  This closes the panel UI port on the host and routes the panel"
echo "  through a Cloudflare Named Tunnel (HTTPS)."
echo ""
warn "  Game-server ports are NOT affected. A Cloudflare tunnel only"
warn "  carries the HTTP panel — players still connect to Host:<port>"
warn "  directly, so those ports stay published on the host."
echo ""

# ── Step 1: Token ─────────────────────────────
step "Step 1/3 — Cloudflare Tunnel token"
echo "  Get one from the Cloudflare dashboard:"
echo "    Zero Trust → Networks → Tunnels → Create a tunnel → Cloudflared"
echo "  Copy the long string after '--token' in the shown install command."
echo ""
read -rp "  Paste tunnel token: " TUNNEL_TOKEN
[ -n "${TUNNEL_TOKEN:-}" ] || { err "Token is required."; exit 1; }

# ── Step 2: Hostname ──────────────────────────
echo ""
step "Step 2/3 — Public hostname"
echo "  The hostname you will map to this tunnel (e.g. panel.example.com)."
echo "  The domain must already be managed by Cloudflare."
echo ""
read -rp "  Public panel hostname: " PUBLIC_HOST
[ -n "${PUBLIC_HOST:-}" ] || { err "Hostname is required."; exit 1; }
# Normalise: strip scheme + trailing slash
PUBLIC_HOST="${PUBLIC_HOST#https://}"; PUBLIC_HOST="${PUBLIC_HOST#http://}"; PUBLIC_HOST="${PUBLIC_HOST%/}"

# ── Persist to .env ───────────────────────────
set_env TUNNEL_TOKEN "$TUNNEL_TOKEN"
set_env APP_PUBLIC_URL "https://${PUBLIC_HOST}"

# ── Step 3: Generate overlay ──────────────────
echo ""
step "Step 3/3 — Generating the compose overlay"
if supports_reset; then
  CLOSE_BLOCK='    ports: !reset []          # host publish removed — panel port fully closed'
  set_env APP_BIND 0.0.0.0
  info "Compose v${COMPOSE_VER} supports '!reset' — panel port fully unpublished."
else
  CLOSE_BLOCK='    # compose < 2.24: cannot drop ports here — panel bound to loopback via APP_BIND=127.0.0.1'
  set_env APP_BIND 127.0.0.1
  warn "Compose v${COMPOSE_VER} < 2.24 — falling back to loopback bind (127.0.0.1)."
fi

cat > "$TUNNEL_FILE" <<YAML
# ─────────────────────────────────────────────
# GENERATED by cloudflared-setup.sh — do not edit by hand.
# Remove with:  ./cloudflared-setup.sh --remove
#
# Closes the panel UI port and runs a Cloudflare tunnel on the
# aethera-net bridge. cloudflared reaches the app at http://app:3000.
# ─────────────────────────────────────────────
services:
  app:
${CLOSE_BLOCK}

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: aethera-cloudflared
    restart: unless-stopped
    profiles: [tunnel]
    command: tunnel --no-autoupdate run --token \${TUNNEL_TOKEN}
    networks:
      - aethera-net
    depends_on:
      - app
YAML

cat > "$PROFILE_FILE" <<PROFILE
# GENERATED by cloudflared-setup.sh — tells run.sh which compose files
# and profiles to layer in. Remove with: ./cloudflared-setup.sh --remove
COMPOSE_FILES="-f ${COMPOSE_FILE} -f ${TUNNEL_FILE}"
COMPOSE_PROFILES="tunnel"
PROFILE

info "Wrote ${TUNNEL_FILE} and ${PROFILE_FILE}"

# ── Bring the stack up with the tunnel ────────
echo ""
step "Bringing the stack up with the tunnel..."
chmod +x run.sh 2>/dev/null || true
./run.sh up

# ── Route instructions ────────────────────────
echo ""
info "✅  cloudflared is running and the panel port is closed on the host."
echo ""
echo -e "${BLUE}── Finish the route in the Cloudflare dashboard ──${NC}"
echo "  1. Zero Trust → Networks → Tunnels → (your tunnel) → Configure"
echo "  2. Open the 'Public Hostname' tab → 'Add a public hostname':"
echo "       Subdomain / Domain : ${PUBLIC_HOST}"
echo "       Type               : HTTP"
echo "       URL                : app:3000"
echo "  3. Save — Cloudflare auto-creates the DNS (CNAME) record."
echo ""
echo "  Panel will be reachable at:  https://${PUBLIC_HOST}"
echo ""
warn "  Reminder: game-server ports are still published on the host."
echo ""
step "Watch tunnel health with:  docker compose logs -f cloudflared"
